version: '3.8'
services:
  frontend:
    build: 
      context: frontend/
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/learn_deploy
    restart: always
    networks:
      - app
    container_name: frontend
    image: streamlit_image
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"] # check HTTP response
      interval: 30s  
      timeout: 10s  
      retries: 3     
      start_period: 20s 


  backend:
    build: 
      context: backend/
    ports:
      - 8000:8000
    volumes:
      - ./backend:/learn_deploy
    restart: always
    networks:
      - app
    container_name: backend
    image: fastapi_image
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/predict"] # check HTTP response
      interval: 30s  # Kiểm tra mỗi 30 giây
      timeout: 10s   # Kiểm tra sẽ thất bại nếu không hoàn thành trong 10 giây
      retries: 3     # Nếu kiểm tra thất bại 3 lần liên tiếp, container sẽ bị đánh dấu là "unhealthy"
      start_period: 30s # Cho container 30 giây để khởi động trước khi bắt đầu kiểm tra

networks:
  app:
    driver: bridge